[tool.pylint.MASTER]
py-version = "3.12"
load-plugins = [
    "pylint.extensions.code_style",
    "pylint.extensions.typing",
]

[tool.pylint."MESSAGES CONTROL"]
# Reasons disabled:
# duplicate-code - unavoidable
disable = [
    "duplicate-code",
]

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = [
    "aioskybell",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true

[tool.pytest.ini_options]
asyncio_mode = "strict"
